name: Send newsletter

on:
  workflow_dispatch:        # 수동 실행
  schedule:
    - cron: "50 23 * * *"   # 매일 08:50 KST (UTC 23:50)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          NEWSAPI_KEY:    ${{ secrets.NEWSAPI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STIBEE_TOKEN:   ${{ secrets.STIBEE_TOKEN }}
          NEWSLETTER_URL: ${{ secrets.NEWSLETTER_URL }}
          CPCOUPANG_KEY:  ${{ secrets.CPCOUPANG_KEY }}   # 쿠팡 Access Key
          CP_TRACK:       ${{ secrets.CP_TRACK }}        # Tracking ID
        run: python src/main.py
